In [1]:
import numpy as np
import pandas as pd

# 1. 2017~2025 데이터 불러오기

### 1-1. 2017

In [2]:
p_17 = pd.read_csv('./data/p17v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\1854510638.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  p_17 = pd.read_csv('./data/p17v32_KMP_csv.csv', encoding="cp949")

In [3]:
p_17_fil = p_17.filter(items=['pid', 'p17gender', 'p17byear', 'p17mar', 'p17income1', 'p17job1', 'p17area', 'p17c01002', 'p17c02003', 'p17a03008'])

In [4]:
p_17_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_17 = p_17_fil

In [5]:
p_17['year'] = 2017

### 1-2. 2018

In [6]:
p_18 = pd.read_csv('./data/p18v32_KMP_csv.csv', encoding="cp949")

In [7]:
p_18_fil = p_18.filter(items=['pid', 'p18gender', 'p18byear', 'p18mar', 'p18income1', 'p18job1', 'p18area', 'p18c01002', 'p18c02003', 'p18a03008'])

In [8]:
p_18_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_18 = p_18_fil

In [9]:
p_18['year'] = 2018

### 1-3. 2019

In [10]:
p_19 = pd.read_csv('./data/p19v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\978969894.py:1: DtypeWarning: Columns (4,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  p_19 = pd.read_csv('./data/p19v32_KMP_csv.csv', encoding="cp949")

In [11]:
p_19_fil = p_19.filter(items=['pid', 'p19gender', 'p19byear', 'p19mar', 'p19income1', 'p19job1', 'p19area', 'p19c01002', 'p19c02003', 'p19a03008'])

In [12]:
p_19_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_19 = p_19_fil

In [13]:
p_19['year'] = 2019

### 1-4. 2020

In [14]:
p_20 = pd.read_csv('./data/p20v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\3310116932.py:1: DtypeWarning: Columns (5,8,9,73) have mixed types. Specify dtype option on import or set low_memory=False.
  p_20 = pd.read_csv('./data/p20v32_KMP_csv.csv', encoding="cp949")

In [15]:
p_20_fil = p_20.filter(items=['pid', 'p20gender', 'p20byear', 'p20mar', 'p20income1', 'p20job1', 'p20area', 'p20c01002', 'p20c02003', 'p20a03008'])

In [16]:
p_20_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_20 = p_20_fil

In [17]:
p_20['year'] = 2020

### 1-5. 2021

In [18]:
p_21 = pd.read_csv('./data/p21v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\2072065319.py:1: DtypeWarning: Columns (5,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  p_21 = pd.read_csv('./data/p21v32_KMP_csv.csv', encoding="cp949")

In [19]:
p_21_fil = p_21.filter(items=['pid', 'p21gender', 'p21byear', 'p21mar', 'p21income1', 'p21job1', 'p21area', 'p21c01002', 'p21c02003', 'p21a03008'])

In [20]:
p_21_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_21 = p_21_fil

In [21]:
p_21['year'] = 2021

### 1-6. 2022

In [22]:
p_22 = pd.read_csv('./data/p22v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\1294024048.py:1: DtypeWarning: Columns (5,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  p_22 = pd.read_csv('./data/p22v32_KMP_csv.csv', encoding="cp949")

In [23]:
p_22_fil = p_22.filter(items=['pid', 'p22gender', 'p22byear', 'p22mar', 'p22income1', 'p22job1', 'p22area', 'p22c01002', 'p22c02003', 'p22a03008'])

In [24]:
p_22_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_22 = p_22_fil

In [25]:
p_22['year'] = 2022

### 1-7. 2023

In [26]:
p_23 = pd.read_csv('./data/p23v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\1970575975.py:1: DtypeWarning: Columns (5,8,9,514) have mixed types. Specify dtype option on import or set low_memory=False.
  p_23 = pd.read_csv('./data/p23v32_KMP_csv.csv', encoding="cp949")

In [27]:
p_23_fil = p_23.filter(items=['pid', 'p23gender', 'p23byear', 'p23mar', 'p23income1', 'p23job1', 'p23area', 'p23c01002', 'p23c02003', 'p23a03008'])

In [28]:
p_23_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_23 = p_23_fil

In [29]:
p_23['year'] = 2023

### 1-8. 2024

In [30]:
p_24 = pd.read_csv('./data/p24v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\738280114.py:1: DtypeWarning: Columns (5,8,9,298,299,300,301,302,303,374,375,376,377) have mixed types. Specify dtype option on import or set low_memory=False.
  p_24 = pd.read_csv('./data/p24v32_KMP_csv.csv', encoding="cp949")

In [31]:
p_24_fil = p_24.filter(items=['pid', 'p24gender', 'p24byear', 'p24mar', 'p24income1', 'p24job1', 'p24area', 'p24c01002', 'p24c02003', 'p24a03008'])

In [32]:
p_24_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_24 = p_24_fil

In [33]:
p_24['year'] = 2024

### 1-9. 2025

In [34]:
p_25 = pd.read_csv('./data/p25v32_KMP_csv.csv', encoding="cp949")

C:\Users\yunu2\AppData\Local\Temp\ipykernel_10024\3389960938.py:1: DtypeWarning: Columns (5,8,9,73,260,281,282,287,292,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531) have mixed types. Specify dtype option on import or set low_memory=False.
  p_25 = pd.read_csv('./data/p25v32_KMP_csv.csv', encoding="cp949")

In [35]:
p_25_fil = p_25.filter(items=['pid', 'p25gender', 'p25byear', 'p25mar', 'p25income1', 'p25job1', 'p25area', 'p25c01002', 'p25c02003', 'p25a03008'])

In [36]:
p_25_fil.columns = ['id', 'gender', 'birth_year', 'mar', 'income', 'job', 'region', 'phone_usage_per_m', 'mobile_bundle', 'telecom']
p_25 = p_25_fil

In [37]:
p_25['year'] = 2025

# 2. 데이터프레임 병합

In [38]:
# 1. 9개년 데이터 묶기
data_frames = [p_17, p_18, p_19, p_20, p_21, p_22, p_23, p_24, p_25]

# 2. 하나로 다 합치기
df_all = pd.concat(data_frames, axis=0, ignore_index=True)
df_all.head()

,id,gender,birth_year,mar,income,job,region,phone_usage_per_m,mobile_bundle,telecom,year
0,10001,1,1967,2,1,2,1,3,2,1,2017
1,10002,2,1972,2,1,2,1,3,2,1,2017
2,20001,1,1965,2,10,1,1,7,1,2,2017
3,30001,1,1971,2,8,1,8,4,2,3,2017
4,30002,2,1974,2,1,2,8,3,2,4,2017

In [39]:
# 3. id 개수
id_counts = df_all['id'].value_counts()

# 4. 9개년 모두 응답한(즉, 9번 등장한) pid만 골라내기
valid_ids = id_counts[id_counts == 9].index

# 5. df_all에서, 9번 모두 등장한 id를 가진 행만 추출
df_balanced = df_all[df_all['id'].isin(valid_ids)].copy()

# 6. 사람별(id), 연도별(year)로 정리
df_tel = df_balanced.sort_values(by=['id', 'year']).reset_index(drop=True)
df_tel.head()

,id,gender,birth_year,mar,income,job,region,phone_usage_per_m,mobile_bundle,telecom,year
0,10002,2,1972,2,1,2,1,3,2,1,2017
1,10002,2,1972,2,1,2,1,4,1,1,2018
2,10002,2,1972,2,1,2,1,6,1,1,2019
3,10002,2,1972,2,1,2,1,4,1,2,2020
4,10002,2,1972,2,1,2,1,4,1,2,2021

# 3. 결측치 처리 및 True/False 변환

In [40]:
df_tel['gender'] = df_tel['gender'].replace({1: 0, 2: 1})
df_tel['job'] = df_tel['job'].replace({1: 1, 2: 0})

In [41]:
df_tel['phone_usage_per_m'].value_counts()

phone_usage_per_m
4       9924
5       9200
6       7319
3       4872
7       4533
2       3304
8       1796
        1075
9       1023
11       453
1        389
10       297
5        138
4        120
6        112
7         80
3         66
2         40
8         40
1         11
9         11
11        10
9999       7
Name: count, dtype: int64

In [42]:
df_tel['mobile_bundle'].value_counts()

mobile_bundle
1    25968
2    17149
      1075
1      504
2      124
Name: count, dtype: int64

In [43]:
df_tel['telecom'].value_counts()

telecom
1    18768
2    10986
3     9179
      5062
4      825
Name: count, dtype: int64

In [44]:
# 1. 빈칸(' ', '')이나 공백을 결측치(NaN)로 변환
df_tel = df_tel.replace(r'^\s*$', np.nan, regex=True)

# 2. 결측치가 하나라도 있는 행의 'id'를 중복 없이 추출
bad_user_ids = df_tel[df_tel.isna().any(axis=1)]['id'].unique()         # 전체 유저 중 결측치를 한 번이라도 낸 유저: 1116명

# 3. 전체 데이터셋에서 블랙리스트에 포함된 id를 가진 모든 행을 삭제
df_tel_clean = df_tel[~df_tel['id'].isin(bad_user_ids)].copy()          # 필터링하고 남은 것: 34776행

# 4. 쪼개져 있던 값들(문자 '1', 숫자 1 등)을 정수형으로 깔끔하게 통일
cols_to_fix = ['telecom', 'mobile_bundle', 'phone_usage_per_m']
df_tel_clean[cols_to_fix] = df_tel_clean[cols_to_fix].astype(int)
df_tel = df_tel_clean.copy()

# 6. 최종 확인
df_tel.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34776 entries, 0 to 44819
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 34776 non-null  int64
 1   gender             34776 non-null  int64
 2   birth_year         34776 non-null  int64
 3   mar                34776 non-null  int64
 4   income             34776 non-null  int64
 5   job                34776 non-null  int64
 6   region             34776 non-null  int64
 7   phone_usage_per_m  34776 non-null  int64
 8   mobile_bundle      34776 non-null  int64
 9   telecom            34776 non-null  int64
 10  year               34776 non-null  int64
dtypes: int64(11)
memory usage: 3.2 MB

In [45]:
df_tel['mobile_bundle'] = df_tel['mobile_bundle'].replace({1: 1, 2: 0})

In [46]:
df_tel['mobile_bundle'].value_counts()

mobile_bundle
1    23033
0    11743
Name: count, dtype: int64

# 4. 이탈여부 열 추가

### 4-1. Target data
- 작년 통신사와 현재 통신사가 달라지는 경우 이탈로 봄

In [47]:
# 1. 정렬 및 변수 세팅
df_tel = df_tel.sort_values(by=['id', 'year']).reset_index(drop=True)
carrier_col = 'telecom' 

# 통신사 이름도 영어로 맞춤
telecom_map = {
    1: 'SKT', 2: 'KT', 3: 'LGU', 4: 'MVNO',
}

# 2. 작년 통신사 끌어오기
df_tel['prev_telecom'] = df_tel.groupby('id')[carrier_col].shift(1)

# 3. 2017년(첫 해) NaN 해결: 빈칸을 '올해 통신사'로 채워서 유지(0)로 간주
df_tel['prev_telecom'] = df_tel['prev_telecom'].fillna(df_tel[carrier_col]).astype(int)

# 4. 이탈 여부 계산
df_tel['telcom_changed'] = np.where(df_tel['prev_telecom'] != df_tel[carrier_col], 1, 0)

# 5. EDA용 영어 상태 변수(churn_status) 만들기
df_tel['prev_name'] = df_tel['prev_telecom'].map(telecom_map)
df_tel['curr_name'] = df_tel[carrier_col].map(telecom_map)

# 유지 = "SKT_Stay", 이탈 = "SKT_to_KT" 형태로 텍스트 생성
df_tel['churn_status_1'] = np.where(
    df_tel['telcom_changed'] == 0,
    df_tel['prev_name'] + '_Stay',  
    df_tel['prev_name'] + '_to_' + df_tel['curr_name']
)

# 6. 임시로 만든 이름 열은 지우고 마무리
df_tel = df_tel.drop(['prev_name', 'curr_name'], axis=1).copy()
df_tel['telcom_changed'] = df_tel['telcom_changed'].fillna(0).astype(int)
df_tel.head()

,id,gender,birth_year,mar,income,job,region,phone_usage_per_m,mobile_bundle,telecom,year,prev_telecom,telcom_changed,churn_status_1
0,10002,1,1972,2,1,0,1,3,0,1,2017,1,0,SKT_Stay
1,10002,1,1972,2,1,0,1,4,1,1,2018,1,0,SKT_Stay
2,10002,1,1972,2,1,0,1,6,1,1,2019,1,0,SKT_Stay
3,10002,1,1972,2,1,0,1,4,1,2,2020,1,1,SKT_to_KT
4,10002,1,1972,2,1,0,1,4,1,2,2021,2,0,KT_Stay

### 4-2. 이탈 방향에 따른 열 추가 (for EDA)

In [48]:
# 1. 딕셔너리
status_dict = {
    'SKT_Stay': 1, 'KT_Stay': 2, 'LGU_Stay': 3, 'MVNO_Stay': 4,
    'SKT_to_KT': 12, 'SKT_to_LGU': 13, 'SKT_to_MVNO': 14,
    'KT_to_SKT': 21, 'KT_to_LGU': 23, 'KT_to_MVNO': 24,
    'LGU_to_SKT': 31, 'LGU_to_KT': 32, 'LGU_to_MVNO': 34, 
    'MVNO_to_SKT': 41, 'MVNO_to_KT': 42, 'MVNO_to_LGU': 43 
}

# 2. 매핑과 동시에 정수형(int)으로 변환하기!
df_tel['churn_status_num_1'] = df_tel['churn_status_1'].map(status_dict).astype(int)

# 3. prev_telecom 열 지우고 원본 데이터(df_tel)에 덮어쓰기
df_tel = df_tel.drop(['prev_telecom'], axis=1).copy()

In [49]:
# 1. 요약용 딕셔너리 생성
simple_dict_1 = {
    'SKT_Stay': 'SKT_stay', 'KT_Stay': 'KT_stay', 'LGU_Stay': 'LGU_stay', 'MVNO_Stay': 'MVNO_stay',
    'SKT_to_KT': 'SKT_churned', 'SKT_to_LGU': 'SKT_churned', 'SKT_to_MVNO': 'SKT_churned',
    'KT_to_SKT': 'KT_churned', 'KT_to_LGU': 'KT_churned', 'KT_to_MVNO': 'KT_churned',
    'LGU_to_SKT': 'LGU_churned', 'LGU_to_KT': 'LGU_churned', 'LGU_to_MVNO': 'LGU_churned',
    'MVNO_to_SKT': 'MVNO_churned', 'MVNO_to_KT': 'MVNO_churned', 'MVNO_to_LGU': 'MVNO_churned'
}

# 2. 새로운 열 추가
df_tel['churn_status_2'] = df_tel['churn_status_1'].map(simple_dict_1)

In [50]:
df_tel.head()

,id,gender,birth_year,mar,income,job,region,phone_usage_per_m,mobile_bundle,telecom,year,telcom_changed,churn_status_1,churn_status_num_1,churn_status_2
0,10002,1,1972,2,1,0,1,3,0,1,2017,0,SKT_Stay,1,SKT_stay
1,10002,1,1972,2,1,0,1,4,1,1,2018,0,SKT_Stay,1,SKT_stay
2,10002,1,1972,2,1,0,1,6,1,1,2019,0,SKT_Stay,1,SKT_stay
3,10002,1,1972,2,1,0,1,4,1,2,2020,1,SKT_to_KT,12,SKT_churned
4,10002,1,1972,2,1,0,1,4,1,2,2021,0,KT_Stay,2,KT_stay

In [51]:
# 1. 요약된 값을 숫자로 바꾸는 새 딕셔너리
final_num_dict = {
    'SKT_stay': 1, 'KT_stay': 2, 'LGU_stay': 3, 'MVNO_stay': 4,
    'SKT_churned': 10, 'KT_churned': 20, 'LGU_churned': 30, 'MVNO_churned': 40
}

# 2. churn_status_2(문자열)를 기반으로 churn_status_num_2(숫자) 생성
df_tel['churn_status_num_2'] = df_tel['churn_status_2'].map(final_num_dict).astype(int)

In [52]:
df_tel.head()

,id,gender,birth_year,mar,income,job,region,phone_usage_per_m,mobile_bundle,telecom,year,telcom_changed,churn_status_1,churn_status_num_1,churn_status_2,churn_status_num_2
0,10002,1,1972,2,1,0,1,3,0,1,2017,0,SKT_Stay,1,SKT_stay,1
1,10002,1,1972,2,1,0,1,4,1,1,2018,0,SKT_Stay,1,SKT_stay,1
2,10002,1,1972,2,1,0,1,6,1,1,2019,0,SKT_Stay,1,SKT_stay,1
3,10002,1,1972,2,1,0,1,4,1,2,2020,1,SKT_to_KT,12,SKT_churned,10
4,10002,1,1972,2,1,0,1,4,1,2,2021,0,KT_Stay,2,KT_stay,2

In [53]:
df_tel.to_csv('tel_preprocessed_ver1.csv', index=False, encoding='utf-8-sig')